spring:
  application:
    name: service-config-client-git-bus
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8892

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh