server:
  port: 9763
eureka:
  instance:
    hostname: peer3
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:9761/eureka/,http://peer2:9762/eureka/
spring:
  application:
    name: eureka-server