spring:
  application:
    name: service-config-server-git-bus
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zt1115798334/SpringcloudConfig.git # 配置git仓库的地址
          search-paths: respo # git仓库地址下的相对地址，可以配置多个，用,分割。
    bus:
      enabled: true
      trace:
        enabled: true
server:
  port: 8890
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

