
spring:
  application:
    name: service-config-server-git #配置服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zt1115798334/SpringcloudConfig.git # 配置git仓库的地址
          search-paths: respo # git仓库地址下的相对地址，可以配置多个，用,分割。
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#/{application}/{profile}[/{label}]
#/{application}-{profile}.yml
#/{label}/{application}-{profile}.yml
#/{application}-{profile}.properties
#/{label}/{application}-{profile}.properties